
FROM nginx:1.29.4

LABEL author: "rafael"
LABEL description: "2048 game served with Nginx"

RUN apt-get update && apt-get install -y git && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/RafaelGarcia-02/docker-hub-2048.git /tmp/2048 && \
    cp -r /tmp/2048/* /usr/share/nginx/html/ && \
    rm -rf /tmp/2048

EXPOSE 80

